### ISSUE TITLE
Calibration algorithm

### ISSUE THREAD

**Issue by FabianL85** [paulplant/xdrip4ios_docs#14]
Hi, 
I'm checking the calibration algorithms of xDrip+ and xDrip4iOS. I would like to understand if both apps use the same algorithm in some way. We are evaluating the accuracy of xDrip apps (Android and iOS) but I'm not sure if they are comparable or if they can be under some particular configuration.
Thanks in advance for any clue

**Comment by paulplant** [comment]
The algorithm used in xDrip4iOS is a port of the one from xDrip from some time ago. It is possible that there have been changes to the calibration algorithms in each app since then.

But this is the repository for the documentation. Any project/development questions related to the app should be raised at:

https://github.com/JohanDegraeve/xdripswift
