### ISSUE TITLE
Nightscout upload not working

### ISSUE THREAD

**Issue by andrewvint** [paulplant/xdrip4ios_docs#19]
i am using xDrip4ios (Shuggah) on my iphone and it doesnt appear to be sending readings to Nightscout.

The connection test passed and i the server is running.

The app is running in Master mode not Follwer mode so not sure what i can do to resolve

**Comment by paulplant** [comment]
Hi @andrewvint , this is the repository for the online documentation, not the actual app itself ;)

For general technical help with that app, please join the Facebook group:

https://www.facebook.com/groups/853994615056838

The issues in GitHub are only for bugs and problems with the app code. (I say this because we know that Nightscout upload works fine so the issue is likely due to your settings or your NS server itself)

**Comment by Petra151064** [comment]
Can you unscribe me?

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Paul Plant ***@***.***>
Verzonden: Friday, September 1, 2023 5:35:33 PM
Aan: paulplant/xdrip4ios_docs ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [paulplant/xdrip4ios_docs] Nightscout upload not working (Issue #19)


Closed #19<https://github.com/paulplant/xdrip4ios_docs/issues/19> as completed.

**Comment by paulplant** [comment]
If you're receiving mails from GitHub about this issue, it's because you subscribed yourself...

There's a button on the right of the screen to unsubscribe.

![image](https://github.com/paulplant/xdrip4ios_docs/assets/37302780/ff1b7f1e-6745-44e3-848b-110890b5dfd3)
